[theme]
base="light"
primaryColor="#4CAF50"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F0F0"
textColor="#000000"
font="sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false